language: java

env:
  global:
    - secure: "qSXbG59qPwiF3NccMohXgkOQIm17ZgclLoqwSD/vFM5Hf6fbhH/Kmks7S7N5\nlVfk0c6q11BDVXOspQF86a07/VmKNMlkb+BhpePvMZAwx9IPYE9eFzTqPkRB\ncUbiPOLZUvaPaVDkoJrjYnawQTkaOwm3oYSMBXQTTI9lXrqs6Xo="

branches:
  except:
    - v3.0-dist
    - master-dist

before_script: 
  - ant test -Djshint.failbuild=true

script:
  - ant

after_success:
  - ./build/post_build.sh
