language: java

env:
  global:
    - secure: "GRy4lDK1/UgwZuJ355ns+43tHPg7AmaIi3F3+v4g+DV8jNuWVw1GcmIIuLuK\nKvdXItZED8iuixog8Jf9GQP1syo4S1LaO/aMxT9OauyO9w21UG8pZe+bRMMP\nFN9hMDcD9KIl5OfNKGpvc0iMTs76RNSRadK519RBObFlaatUXuM="

branches:
  except:
    - v3.0-dist
    - master-dist

before_script: 
  - ant test -Djshint.failbuild=true

script:
  - ant

after_success:
  - ./build/post_build.sh
